### ISSUE TITLE
if to switch

### ISSUE THREAD

**Issue by UmerSharif** [HAZberi/the-memory-game#2]
The if statement could be switch. Just a suggestion but its a preference. dont worry about it through. looks great.
at code block: 44 to 48. switch is a  bit more readable and less verbose.

[Article](https://www.kirupa.com/html5/conditional_statements_if_else_switch_javascript.htm#:~:text=As%20we%20can%20see%2C%20if,in%20an%20if%20%2F%20else%20statement.)

**Comment by HAZberi** [comment]
Noted Bro! Never thought about switch. It's a good case!!
